In [1]:
import pandas as pd 
import numpy as np 
import torch

In [2]:
a = np.array([1, 2, 3, 4])
b = np.array([[5, 6, 7, 8], [9, 10, 11, 12]])
a

array([1, 2, 3, 4])

In [3]:
b

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [4]:
c = a + b
c

array([[ 6,  8, 10, 12],
       [10, 12, 14, 16]])

In [6]:
print ('Hello!')

Hello!


In [7]:
print(a, b)

[1 2 3 4] [[ 5  6  7  8]
 [ 9 10 11 12]]
